<a href="https://colab.research.google.com/github/juliakaneko/Micro-Credential-Winter-2022/blob/main/Day_5_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy (or Numpy) is a Pyhton Library or Module design for Linear Algebra and Statistical Computation.
It is one of the most important modules in python for Data Science since most all of the libraries necessary for  rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to other programming language libraries such as C++. 

_______________________________

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We will not have the time to cover them all; we will, however, focus on some of the most important topics such as vectors, arrays, matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main objects that we will use in this class. 

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
#A list is a data structure that supports several operations.
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
#An array is a method of organizing data in a memory device.
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
#Lists out all of the numbers from 0-19
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
#Lists out every second number from 0-109
np.arange(0,110,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
#Lists 5 items of 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
#List of 15 rows with 15 columns filled with 0
np.zeros((15,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [12]:
#Lists 30 items of one
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#List of 30 with 30 items
np.ones((30,30))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
#Splits the number from 0-100 into 5 sections
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [15]:
#Splits the number from 0-10 into 50 sections
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

An identity matrix is a square matrix in which the elements of the main diagonal are equal to one and the other elements equal to zero

In [16]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
'''
Return a matrix with random elements uniformly distributed
on the interval (0, 1). The arguments are handled the same
as the arguments for `eye'.
'''
np.random.rand(5)

array([0.43265218, 0.33485792, 0.87471703, 0.54927507, 0.21429184])

In [18]:
np.random.rand(10,10)

array([[0.71477762, 0.35844205, 0.97110051, 0.80217091, 0.99391102,
        0.67089045, 0.11924835, 0.99040968, 0.75524155, 0.44123753],
       [0.81743178, 0.37784778, 0.53243196, 0.5477615 , 0.78432898,
        0.76391879, 0.38350216, 0.99226569, 0.51222389, 0.70964841],
       [0.36886204, 0.7512845 , 0.57381064, 0.48639892, 0.30022044,
        0.79857611, 0.18705757, 0.49780442, 0.71228561, 0.01006244],
       [0.10232371, 0.98099654, 0.24362924, 0.0433193 , 0.21418063,
        0.72324369, 0.91210863, 0.25226873, 0.84009594, 0.31214451],
       [0.15214977, 0.07633842, 0.40640841, 0.03166564, 0.34814383,
        0.18211539, 0.52341895, 0.44649506, 0.68844549, 0.50617853],
       [0.88304708, 0.48793276, 0.63526755, 0.57096612, 0.93809825,
        0.95436715, 0.98873319, 0.02961065, 0.81606016, 0.96849013],
       [0.17028799, 0.0642806 , 0.49069547, 0.67026701, 0.89767555,
        0.26739961, 0.68570028, 0.76166489, 0.20453714, 0.43060938],
       [0.11282328, 0.81398857, 0.8272050

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [19]:
'''
Returns a matrix with normally distributed pseudo-random elements 
having zero mean and variance one. The arguments are handled the
same as the arguments for `rand'.
'''
#Includes negative numbers?
np.random.randn(20)

array([-1.39259425,  0.54912009, -1.84240508, -0.63050462,  0.37133986,
        0.61778748, -0.87403693, -1.05393525,  0.84044518,  0.7235758 ,
        1.64129792, -0.30540525, -0.18696484, -0.44207856, -0.10352883,
       -0.42932543, -1.16444221, -0.61640811, -0.60115908, -0.21934154])

In [20]:
np.random.randn(5,5)

array([[-0.33726611,  0.83919357, -0.77749117, -0.88473846,  0.48457251],
       [ 0.36689508,  0.36842829, -1.87199818,  0.61201465,  1.29450525],
       [ 0.35729352, -0.75384214,  0.78466284,  0.66271706, -0.22209015],
       [-1.00268453,  0.83610018, -0.27069891, -0.57545244,  1.20094738],
       [ 0.59380805, -0.75227208, -0.04710112, -1.58535394,  1.04082651]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
#A random integer in range [start, end] including the end points.
np.random.randint(1,500)

282

In [22]:
#Picks 100 random numbers from 1-999
np.random.randint(1,1000,100)

array([442, 255, 194, 421, 192, 520, 424, 130, 374, 612, 312,  28, 878,
       296, 326,  38, 781, 809, 533, 507, 852, 164, 532,  40, 327, 903,
       811, 652, 327, 432, 422, 877, 611, 964, 385, 712, 770, 853, 111,
       856, 204, 412, 743, 452, 635, 805, 256, 342, 557,  50, 410, 711,
       184, 262, 272, 811, 542, 899, 644, 479, 576, 883, 213, 195, 873,
       335, 407,  83, 751, 950, 718,  51, 763, 799, 127, 657, 242, 148,
       171, 185, 194, 423,  81,  62, 226, 222, 412, 346, 475, 165, 994,
       929, 982, 396, 788, 204, 290, 525, 772, 799])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [23]:
arr = np.arange(50)
ranarr = np.random.randint(0,500,10)

In [24]:
#Lists all the numbers from 1-50
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
ranarr

array([239, 265, 436, 473, 308,  61, 247, 127, 348, 270])

## Reshape
Returns an array containing the same data with a new shape.

In [26]:
#Creates 10 rows with 5 columns in each line
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [27]:
ranarr

array([239, 265, 436, 473, 308,  61, 247, 127, 348, 270])

In [28]:
ranarr.max()

473

In [29]:
#Picks the position where the ran arr.mac() number is
ranarr.argmax()

3

In [30]:
ranarr.min()

61

In [31]:
#Picks the position where the ran arr.min() number is
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [32]:
# Vector
arr.shape

(50,)

In [33]:
# Notice the two sets of brackets
# Lists 2 rows of 25 columns starting from 0
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
# Matrix?
arr.reshape(2,25).shape

(2, 25)

In [35]:
#Lists 25 lines with 2 items in each line
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [36]:
arr.reshape(25,2).shape

(25, 2)

### dtype

You can also grab the data type of the object in the array:

In [37]:
#32 bit integers
arr.dtype

dtype('int64')

# Good Times!