<a href="https://colab.research.google.com/github/juliakaneko/Micro-Credential-Winter-2022/blob/main/Day_5_Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Numpt

In [3]:
import numpy as np

In [6]:
#np.array takes a list
np_city = np.array(['NYC','LA','Miami','Houston'])

In [10]:
np_city.shape

(4,)

In [12]:
#4 like the number of items in the np.array list
np_city.size

4

In [13]:
np_city.dtype

dtype('<U7')

In [15]:
np_city2 = np.array([['NYC','LA','Miami','Houston'],
                     ['NY','CA','FL','TX']])

In [19]:
# 2 lists with 4 elements each
np_city2.shape

(2, 4)

In [21]:
# In total 8 items
np_city2.size

8

In [20]:
np_city.dtype

dtype('<U7')

In [22]:
# Create a np.array with 5 list in it...
# each list must have 10 items in it

In [61]:
np_animals = ([['pugs', 'pomeranian', 'german shepard', 'poodle', 'bulldog', 'husky', 'labrador retriever', 'Pit bull terrier', 'shiba', 'dobermann'],
              ['persian', 'maine coon', 'bengal', 'british short hair', 'siamese', 'sphinx', 'ragdoll', 'munchkin', 'scottish fold', 'norwegian forest cat'], 
              ['python', 'cobras', 'vipers', 'anaconda', 'titanoboa', 'kingsnakes', 'garter', 'coral reef', 'taipan', 'colubrid'],
              ['a','b','c','d','e','f','g','h','i','j'],
              ['a','b','c','d','e','f','g','h','i','j']])

In [64]:
np_animals.size

AttributeError: ignored

## Basic Operations

In [27]:
first_trial_cyclist = [10, 15, 17, 26, 37, 49, 57, 61]

In [28]:
second_trial_cyclist = [11, 45, 65, 24, 23, 45, 90, 99]

In [29]:
np_first_trial = np.array(first_trial_cyclist)
np_second_trial = np.array(second_trial_cyclist)

In [32]:
#Adds the 2 items in the sample place in each list
np_first_trial + np_second_trial

array([ 21,  60,  82,  50,  60,  94, 147, 160])

In [34]:
#15*45
np_first_trial[1] * np_second_trial[5]

675

## Accesing array elements - indexing

In [36]:
#Two dimentional array
cyclist_trial = np.array([[10, 15, 17, 26],[12, 11, 21, 24]])

In [38]:
first_trial = cyclist_trial[0]

In [39]:
first_trial

array([10, 15, 17, 26])

In [41]:
newlist = ['string1','string2']

In [43]:
newlist[0]

'string1'

In [44]:
newlist[0][2]

'r'

In [59]:
second_trial = cyclist_trial[1]

In [60]:
second_trial

array([12, 11, 21, 24])

In [48]:
#this is the same as saying cyclist_trial[0][1]
first_trial[1]

15

In [49]:
cyclist_trial[0][1]

15

## Boolean Arrays

In [54]:
test_score = np.array([[83,71,67,63],
                       [54,68,81,45]])

In [55]:
passed = test_score > 60

In [56]:
passed

array([[ True,  True,  True,  True],
       [False,  True,  True, False]])

##Copy and View

In [57]:
test2_scores = test_score

In [58]:
test_score is test2_scores

True

In [89]:
test2_scores[1][3] = 78

In [92]:
#The 4th item in the 2nd line has turned from 45 to 78
test2_scores

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [93]:
test_score

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

## Array (Boroughs)

In [100]:
NYC_Boroughs = np.array (['Manhattan', 'Brooklyn','Queens','Bronx','Staten Island'])

In [101]:
#Original dataset
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'],
      dtype='<U13')

In [102]:
#Creating a shallow copy
NY_Boroughs = NYC_Boroughs.view()

In [103]:
#Counts the number of items in the list
len(NY_Boroughs)

5

In [104]:
#Changes the item number 4 from Staten Island to Central Park
NY_Boroughs[4] = 'Central Park'

In [105]:
len(NY_Boroughs)

5

In [106]:
#Assigned dataset
NY_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [107]:
NYC_Boroughs is NY_Boroughs
#If you try to do a is func

False

In [108]:
NYC = NYC_Boroughs.copy()

In [109]:
NYC[4] = 'Astoria'

In [110]:
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [111]:
NYC 

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Astoria'],
      dtype='<U13')